version: "1.0"

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: luccasaps/libraryapi:latest
    container_name: library-api
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/librarydb
      DATASOURCE_USER: user
      DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: producao
    depends_on:
      - db
volumes:
  postgres-data: