spring:
  application:
    name: JPA
  output:
    ansi:
      enabled: ALWAYS


  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    com:
      luccasaps:
        jpa: trace
    org:
      springframework:
        web: debug
        security: trace

# hierarquia:
# trace (mais detalhado, abrange todos os niveis a baixo)
# debug
# info
# warn
# error


springdoc:
  override-with-generic-response: false

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
